name: Demo to create automatic Pull request
on:
  push:
    branches:
      - main
    paths:
      - '**.txt'
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
     
     
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      
      - name: Raise PR 
        id: demo-1
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-pr-branch23
          base: main
          title: demo for auto pr
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL
            }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body: This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: "vijay.mishra@nintheast.com"
          
          delete-branch: true
