name: Demo to create automatic Pull request
on:
  push:
    branches:
      - main
    paths:
      - '**.txt'
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR_FIle1
     
      - name: Raise PR 
        id: demo
        uses: marvinjberg/pull-request-creator@v3
        with:
          branch: TestPR125
          base: main
          title: demo for auto pr
          
          body: This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: "vijay.mishra@nintheast.com"
          delete-branch: true

      - name: Get the sha element of the base and head branches
        run: |
          BASE_SHA=$(git rev-parse ${{ github.event.pull_request.base.sha }})
          HEAD_SHA=$(git rev-parse ${{ github.event.pull_request.head.sha }})

      - name: Compare the sha elements
        run: |
          git diff --name-only $BASE_SHA $HEAD_SHA

      - name: Use git diff to create the diff
        run: |
          git diff $BASE_SHA $HEAD_SHA > diff.txt

      - name: Redirect the output of git diff to a file
        run: |
          cat diff.txt

  
