name: Demo to create automatic Pull request
on:
  push:
    branches:
      - main
    paths:
      - '**.yml'
jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2
      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x
      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR_FIle
     
      - name: Raise PR 
        id: demo
        uses: peter-evans/create-pull-request@v3
        with:
          branch: TestPR
          base: main
          title: demo for auto pr
          
          body: This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: "vijay.mishra@nintheast.com"
          
          delete-branch: true
